#!/usr/bin/env node
/**
 * Copy the Pyodide distribution out of node_modules into public/pyodide/ so the
 * app serves the WebAssembly runtime from its own origin instead of a CDN.
 *
 * Rationale in docs/architecture.md §1.1: the Pyodide payload *is* the code
 * execution environment, the same package supplies the browser runtime and the
 * Node test runner (so CI and learners execute on identical builds), and public
 * CDNs are blocked on some school and corporate networks.
 *
 * The copy is generated, never committed (see .gitignore). It is idempotent and
 * skips files whose size already matches, so repeated dev restarts are cheap.
 */
import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";

const require = createRequire(import.meta.url);
const here = path.dirname(new URL(import.meta.url).pathname);
const destDir = path.join(here, "..", "public", "pyodide");

/** Files Pyodide needs at runtime. Deliberately explicit: we do not want to ship
 * the 8 MB source maps or the bundled demo consoles to learners. */
const REQUIRED = ["pyodide.mjs", "pyodide.asm.mjs", "pyodide.asm.wasm", "python_stdlib.zip"];
const OPTIONAL = ["pyodide-lock.json", "pyodide.d.ts", "ffi.d.ts"];

function resolveSourceDir() {
  try {
    return path.dirname(require.resolve("pyodide/package.json"));
  } catch {
    return null;
  }
}

function main() {
  const srcDir = resolveSourceDir();
  if (!srcDir) {
    console.error(
      "[sync-pyodide] Could not resolve the 'pyodide' package. Run `npm install` first.",
    );
    process.exit(1);
  }

  fs.mkdirSync(destDir, { recursive: true });

  let copied = 0;
  let skipped = 0;
  for (const name of [...REQUIRED, ...OPTIONAL]) {
    const src = path.join(srcDir, name);
    if (!fs.existsSync(src)) {
      if (REQUIRED.includes(name)) {
        console.error(`[sync-pyodide] Required file missing from the pyodide package: ${name}`);
        process.exit(1);
      }
      continue;
    }
    const dest = path.join(destDir, name);
    const srcStat = fs.statSync(src);
    if (fs.existsSync(dest) && fs.statSync(dest).size === srcStat.size) {
      skipped += 1;
      continue;
    }
    fs.copyFileSync(src, dest);
    copied += 1;
  }

  const version = require("pyodide/package.json").version;
  fs.writeFileSync(
    path.join(destDir, "VERSION"),
    `${version}\nGenerated by scripts/sync-pyodide.mjs. Do not edit or commit.\n`,
  );

  // Two more runtime assets are published alongside the interpreter:
  //
  //   harness.py — the single implementation of grading semantics. Its source of
  //     truth is src/lib/python/harness.py, which the Node test runner loads
  //     directly, so browser and CI grade with the same file.
  //
  //   worker.js — the module worker that drives Pyodide. It is served rather
  //     than bundled because the bundler emits a *classic* worker, which Pyodide
  //     refuses to initialise in. See the header of src/lib/python/worker.js.
  const pythonSrcDir = path.join(here, "..", "src", "lib", "python");
  const pythonDestDir = path.join(here, "..", "public", "python");
  fs.mkdirSync(pythonDestDir, { recursive: true });
  for (const name of ["harness.py", "worker.js"]) {
    fs.copyFileSync(path.join(pythonSrcDir, name), path.join(pythonDestDir, name));
  }

  console.log(
    `[sync-pyodide] Pyodide ${version} ready in public/pyodide (${copied} copied, ${skipped} up to date); harness.py and worker.js published.`,
  );
}

main();
